### ISSUE TITLE
反复刷新，踢人，会导致ws crash，原因是多次close已经被close的socket

### ISSUE THREAD

**Issue by TQCasey** [OpenIMSDK/Open-IM-SDK-Core#12]
`
func NewWs(wsRespAsyn *WsRespAsyn, wsConn *WsConn, cmdCh chan common.Cmd2Value, pushMsgAndMaxSeqCh chan common.Cmd2Value, cmdHeartbeatCh chan common.Cmd2Value) *Ws {

	defer func() {
		if err := recover(); err != nil {
			log.Warn("recover from panic for NewWS func")
		}
	} () // 加一个捕获就可以

	p := Ws{WsRespAsyn: wsRespAsyn, WsConn: wsConn, cmdCh: cmdCh, pushMsgAndMaxSeqCh: pushMsgAndMaxSeqCh, cmdHeartbeatCh: cmdHeartbeatCh}
	go p.ReadData()

	return &p
}`

**Comment by skiffer-git** [comment]
fixed
