### ISSUE TITLE
好友删除bug，没有回调

### ISSUE THREAD

**Issue by TQCasey** [OpenIMSDK/Open-IM-SDK-Core#13]
如题，server是给了resp的，但是SDK里面的 判断貌似出了个小问题

friendDeletedNotification 这个函数 ，应该是判断 toUserID == f.loginUserID 

-	if detail.FromToUserID.FromUserID == f.loginUserID {
+	if detail.FromToUserID.ToUserID == f.loginUserID {
 		f.SyncFriendList(operationID)
 		return
 	}

**Comment by skiffer-git** [comment]
a delete b , a is FromUserID , b is ToUserID
